manifests/bh/general/universalsearch/0.8.1.json
=> Universal Search Release v0.8.1

manifests/estreya/bh/liveMap/1.2.2.json
=> Live Map Release v1.2.2

manifests/estreya/bh/tradingPostWatcher/1.1.2.json
=> Trading Post Watcher Release v1.1.2

manifests/estreya/bh/scrollingCombatText/1.1.2.json
=> Scrolling Combat Text Release v1.1.2

manifests/estreya/bh/webhookUpdater/1.2.1.json
=> Webhook Updater Release v1.2.1

manifests/Nekres/Regions_Of_Tyria/0.6.19.json
=> Regions of Tyria Release v0.6.19

manifests/bh/community/pathing/1.2.9.json
=> Pathing Release v1.2.9

manifests/Lorf/BH/TTBlockersStuff/0.3.2-alpha.json
=> TTBlockersStuff Release v0.3.2-alpha

manifests/Nekres/Mistwar/1.4.7.json
=> Mistwar Release v1.4.7

manifests/Kenedia/Modules/Characters/1.0.18.json
=> Characters Release v1.0.18

manifests/bh/community/pathing/1.2.10.json
=> Pathing Release v1.2.10

manifests/KillProofModule/2.21.4.json
=> Proof Logix Release v2.21.4

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.16.json
=> Fishing Buddy Release v1.0.16

manifests/Soeed/RaidClears/2.2.3.json
=> Clears Tracker Release v2.2.3

manifests/ecksofa/gatheringtools/1.4.1.json
=> Gathering Tools Release v1.4.1

manifests/ecksofa/sessiontracker/1.3.2.json
=> Session Tracker Release v1.3.2

manifests/japyx/kprefresher/1.5.1.json
=> KpRefresher Release v1.5.1

manifests/xyz/f3l1x/blishemotes/1.0.1.json
=> Emotes Release v1.0.1

manifests/Kenedia/Modules/Characters/1.0.19.json
=> Characters Release v1.0.19

manifests/KillProofModule/2.21.5.json
=> Proof Logix Release v2.21.5

manifests/Kenedia/Modules/Characters/1.0.20.json
=> Characters Release v1.0.20

manifests/Kenedia/Modules/QoL/1.0.0.json
=> Tyrian QoL Release v1.0.0

manifests/Kenedia/Modules/Characters/1.0.21.json
=> Characters Release v1.0.21

manifests/Manlaan/CommanderMarkers/3.0.0.json
=> Commander Markers Release v3.0.0

manifests/Kenedia/Modules/Characters/1.0.23.json
=> Characters Release v1.0.23

manifests/Soeed/HappyReset/1.0.0.json
=> Happy Reset Release v1.0.0

manifests/Nekres/Music_Mixer/1.0.1.json
=> Mount Music Release v1.0.1

manifests/Nekres/Music_Mixer/1.0.2.json
=> Mount Music Release v1.0.2

manifests/Nekres/Music_Mixer/1.0.4.json
=> Mount Music Release v1.0.4

manifests/xyz/f3l1x/blishemotes/1.0.2.json
=> Emotes Release v1.0.2

manifests/Nekres/Music_Mixer/1.0.5.json
=> Mount Music Release v1.0.5

manifests/Kiroho/Joka/EmoteTome/1.0.1.json
=> EmoteTome Release v1.0.1

manifests/Kiroho/Joka/EmoteTome/1.0.2.json
=> EmoteTome Release v1.0.2

manifests/Kiroho/Joka/EmoteTome/1.0.3.json
=> EmoteTome Release v1.0.3

manifests/xyz/f3l1x/blishemotes/1.1.0.json
=> Emotes Release v1.1.0

manifests/Nekres/Music_Mixer/1.1.0.json
=> Mount Music Release v1.1.0

manifests/estreya/bh/scrollingCombatText/1.2.0.json
=> Scrolling Combat Text Release v1.2.0

manifests/estreya/bh/eventTable/3.5.0.json
=> Event Table Release v3.5.0

manifests/Nekres/Music_Mixer/1.1.4.json
=> Mount Music Release v1.1.4

manifests/Kenedia/Modules/Characters/1.0.24.json
=> Characters Release v1.0.24

manifests/Taimi/UndaDaSea_BlishHUD/2.0.4.json
SSRD Build Triggered by Tiny Taimi
=> Unda Da Sea Release v2.0.4

manifests/Nekres/Music_Mixer/1.1.6.json
=> Mount Music Release v1.1.6

manifests/Denrage/AchievementTrackerModule/0.1.8.json
=> Achievement Tracker Release v0.1.8

manifests/bh/general/events/1.0.1.json
=> Events and Metas Observer Release v1.0.1

manifests/Nekres/Regions_Of_Tyria/0.7.1.json
=> Regions of Tyria Release v0.7.1

manifests/Nekres/Regions_Of_Tyria/0.8.0.json
=> Regions of Tyria Release v0.8.0

manifests/Nekres/Regions_Of_Tyria/0.8.1.json
=> Regions of Tyria Release v0.8.1

manifests/Nekres/Regions_Of_Tyria/0.8.2.json
=> Regions of Tyria Release v0.8.2

manifests/Nekres/Regions_Of_Tyria/0.8.3.json
=> Regions of Tyria Release v0.8.3

manifests/Nekres/Regions_Of_Tyria/0.9.0.json
=> Regions of Tyria Release v0.9.0

manifests/ecksofa/sessiontracker/2.0.0.json
=> Session Tracker Release v2.0.0

manifests/Nekres/Regions_Of_Tyria/0.10.1.json
=> Regions of Tyria Release v0.10.1

manifests/Nekres/Regions_Of_Tyria/0.11.0.json
=> Regions of Tyria Release v0.11.0

manifests/Nekres/Music_Mixer/1.1.9.json
=> Mount Music Release v1.1.9

manifests/Lorf/BH/TTBlockersStuff/0.4.0-alpha.json
=> TTBlockersStuff Release v0.4.0-alpha

manifests/ecksofa/sessiontracker/2.1.0.json
=> Session Tracker Release v2.1.0

manifests/Nekres/Regions_Of_Tyria/0.12.3.json
=> Regions of Tyria Release v0.12.3

manifests/Denrage/AchievementTrackerModule/0.1.9.json
=> Achievement Tracker Release v0.1.9

manifests/Manlaan/CommanderMarkers/3.2.1.json
=> Commander Markers Release v3.2.1

manifests/Soeed/HappyReset/1.0.1.json
=> Happy Reset Release v1.0.1

manifests/xyz/f3l1x/blishemotes/1.2.1.json
=> Emotes Release v1.2.1

manifests/Kenedia/Modules/QoL/1.0.2.json
=> Tyrian QoL Release v1.0.2

manifests/estreya/bh/eventTable/3.5.1.json
=> Event Table Release v3.5.1

manifests/Kenedia/Modules/QoL/1.0.4.json
=> Tyrian QoL Release v1.0.4

manifests/Kenedia/Modules/QoL/1.0.5.json
=> Tyrian QoL Release v1.0.5

manifests/ecksofa/sessiontracker/2.2.0.json
=> Session Tracker Release v2.2.0

manifests/Nekres/Chat_Shorts/0.9.16.json
=> Chat Shorts Release v0.9.16

manifests/Nekres/Chat_Shorts/0.9.18.json
=> Chat Shorts Release v0.9.18

manifests/ecksofa/sessiontracker/2.3.0.json
=> Session Tracker Release v2.3.0

manifests/Nekres/Chat_Shorts/0.9.19.json
=> Chat Shorts Release v0.9.19

manifests/estreya/bh/eventTable/3.5.2.json
=> Event Table Release v3.5.2

manifests/Nekres/Chat_Shorts/0.11.5.json
=> Chat Shorts Release v0.11.5

manifests/Nekres/Chat_Shorts/0.11.7.json
=> Chat Shorts Release v0.11.7

manifests/ecksofa/sessiontracker/3.0.0.json
=> Session Tracker Release v3.0.0

manifests/Nekres/Chat_Shorts/0.13.1.json
=> Chat Shorts Release v0.13.1

manifests/Nekres/Chat_Shorts/0.13.3.json
=> Chat Shorts Release v0.13.3

manifests/bh/community/etm/4.0.1.json
=> Error Submission Module Release v4.0.1

manifests/Nekres/Chat_Shorts/0.13.4.json
=> Chat Shorts Release v0.13.4

manifests/estreya/bh/eventTable/3.6.0.json
=> Event Table Release v3.6.0

manifests/Nekres/Chat_Shorts/0.13.8.json
=> Chat Shorts Release v0.13.8

manifests/Nekres/Chat_Shorts/0.14.2.json
=> Chat Shorts Release v0.14.2

manifests/com/shooper/ddr/1.2.1.json
=> Dance Dance Rotation Release v1.2.1

manifests/ecksofa/sessiontracker/5.0.0.json
=> Session Tracker Release v5.0.0

manifests/ecksofa/sessiontracker/6.0.0.json
=> Session Tracker Release v6.0.0

manifests/com/shooper/ddr/1.3.1.json
=> Dance Dance Rotation Release v1.3.1

manifests/ecksofa/sessiontracker/7.0.0.json
=> Session Tracker Release v7.0.0

manifests/Manlaan/Mounts/1.4.0.json
=> Mounts & More Release v1.4.0

manifests/Soeed/RaidClears/2.3.1.json
=> Clears Tracker Release v2.3.1

manifests/Manlaan/Mounts/1.4.1.json
=> Mounts & More Release v1.4.1

manifests/japyx/kprefresher/1.5.2.json
=> KpRefresher Release v1.5.2

manifests/bh/general/events/1.0.2.json
=> Events and Metas Observer Release v1.0.2

manifests/Nekres/Quick_Surrender_Module/0.2.5.json
=> Quick Surrender Release v0.2.5

manifests/Nekres/Quick_Surrender_Module/0.2.7.json
=> Quick Surrender Release v0.2.7

manifests/bh/community/pathing/1.4.0.json
=> Pathing Release v1.4.0

manifests/Manlaan/CommanderMarkers/3.2.2.json
=> Commander Markers Release v3.2.2

manifests/Manlaan/Mounts/1.4.2.json
=> Mounts & More Release v1.4.2

manifests/Kiroho/Joka/EmoteTome/1.1.1.json
=> EmoteTome Release v1.1.1

manifests/Manlaan/Mounts/1.4.3.json
=> Mounts & More Release v1.4.3

manifests/Manlaan/Mounts/1.4.4.json
=> Mounts & More Release v1.4.4

manifests/estreya/bh/portalDistance/1.0.0.json
=> Portal Distance Release v1.0.0

manifests/ecksofa/sessiontracker/8.0.0.json
=> Session Tracker Release v8.0.0

manifests/bh/community/pathing/1.4.1.json
=> Pathing Release v1.4.1

manifests/Manlaan/Mounts/1.4.5.json
=> Mounts & More Release v1.4.5

manifests/Manlaan/Mounts/1.4.6.json
=> Mounts & More Release v1.4.6

manifests/estreya/bh/eventTable/3.6.2.json
=> Event Table Release v3.6.2

manifests/Manlaan/Mounts/1.4.8.json
=> Mounts & More Release v1.4.8

manifests/bh/general/universalsearch/0.9.0.json
=> Universal Search Release v0.9.0

manifests/estreya/bh/webhookUpdater/1.2.2.json
=> Webhook Updater Release v1.2.2

manifests/bh/community/pathing/1.5.0.json
=> Pathing Release v1.5.0

manifests/estreya/bh/eventTable/3.6.4.json
=> Event Table Release v3.6.4

manifests/estreya/bh/portalDistance/1.0.1.json
=> Portal Distance Release v1.0.1

manifests/bh/community/pathing/1.5.1.json
=> Pathing Release v1.5.1

manifests/com/shooper/ddr/1.3.0.json
=> Dance Dance Rotation Release v1.3.0

manifests/estreya/bh/eventTable/3.6.5.json
=> Event Table Release v3.6.5

manifests/xyz/f3l1x/blishemotes/1.3.0.json
=> Emotes Release v1.3.0

manifests/Ideka/RacingMeter/1.9.2.json
=> Racing Meter Release v1.9.2

manifests/HexedHero/Blish_HUD/FlipperHelper/1.0.0.json
=> Flipper Helper Release v1.0.0

manifests/estreya/bh/eventTable/3.6.6.json
=> Event Table Release v3.6.6

manifests/HexedHero/Blish_HUD/FlipperHelper/1.1.0.json
=> Flipper Helper Release v1.1.0

manifests/HexedHero/Blish_HUD/FlipperHelper/1.1.1.json
=> Flipper Helper Release v1.1.1

manifests/bh/general/loadingscreenhints/1.1.2.json
=> Loading Screen Hints Release v1.1.2

manifests/bh/general/loadingscreenhints/1.1.5.json
=> Loading Screen Hints Release v1.1.5

manifests/bh/general/loadingscreenhints/1.1.8.json
=> Loading Screen Hints Release v1.1.8

manifests/bh/general/loadingscreenhints/1.2.1.json
=> Loading Screen Hints Release v1.2.1

manifests/Soeed/RaidClears/2.4.0.json
=> Clears Tracker Release v2.4.0

manifests/Soeed/HappyReset/1.0.2.json
=> Happy Reset Release v1.0.2

manifests/HexedHero/Blish_HUD/FlipperHelper/2.0.0.json
=> Flipper Helper Release v2.0.0

manifests/bh/general/loadingscreenhints/1.3.0.json
=> Loading Screen Hints Release v1.3.0

manifests/HexedHero/Blish_HUD/FlipperHelper/2.1.0.json
=> Flipper Helper Release v2.1.0

manifests/Tortle/PlayerMarker/1.1.1.json
SSRD Build Triggered by LuckyTortle
=> Player Marker Release v1.1.1

manifests/estreya/bh/tradingPostWatcher/1.1.3.json
=> Trading Post Watcher Release v1.1.3

manifests/HexedHero/Blish_HUD/FlipperHelper/2.2.0.json
=> Flipper Helper Release v2.2.0

manifests/Ideka/MistsQuill/2.5.1.json
=> Quill of the Mists Release v2.5.1

manifests/estreya/bh/tradingPostWatcher/1.1.4.json
=> Trading Post Watcher Release v1.1.4

manifests/estreya/bh/eventTable/3.7.0.json
=> Event Table Release v3.7.0

manifests/MysticCrafting/Module/1.0.0.json
=> Mystic Crafting Release v1.0.0

manifests/HexedHero/Blish_HUD/FlipperHelper/2.3.0.json
=> Flipper Helper Release v2.3.0

manifests/HexedHero/Blish_HUD/FlipperHelper/2.3.1.json
=> Flipper Helper Release v2.3.1

manifests/Manlaan/Mounts/1.4.9.json
=> Mounts & More Release v1.4.9

manifests/Manlaan/Mounts/1.4.10.json
=> Mounts & More Release v1.4.10

manifests/MysticCrafting/Module/1.1.2.json
=> Mystic Crafting Release v1.1.2

manifests/HexedHero/Blish_HUD/MarkerPackAssistant/1.0.3.json
=> Marker Pack Assistant Release v1.0.3

manifests/Ideka/CustomCombatText/0.1.2.json
=> Custom Combat Text Release v0.1.2

manifests/Nekres/FailScreens/0.2.1.json
=> Fail Screens Release v0.2.1

manifests/HexedHero/Blish_HUD/MarkerPackAssistant/1.0.4.json
=> Marker Pack Assistant Release v1.0.4

manifests/estreya/bh/eventTable/3.8.0.json
=> Event Table Release v3.8.0

manifests/MysticCrafting/Module/1.2.0.json
=> Mystic Crafting Release v1.2.0

manifests/MysticCrafting/Module/1.2.1.json
=> Mystic Crafting Release v1.2.1

manifests/bh/community/pathing/1.6.3.json
=> Pathing Release v1.6.3

manifests/estreya/bh/eventTable/3.9.0.json
=> Event Table Release v3.9.0

manifests/Charr/Timers_BlishHUD/0.3.22.json
=> Timers Release v0.3.22

manifests/Charr/Timers_BlishHUD/0.3.23.json
=> Timers Release v0.3.23

manifests/estreya/bh/portalDistance/1.0.2.json
=> Portal Distance Release v1.0.2

manifests/Manlaan/CommanderMarkers/3.3.0.json
=> Commander Markers Release v3.3.0

manifests/Soeed/RaidClears/2.5.0.json
=> Clears Tracker Release v2.5.0

manifests/estreya/bh/tradingPostWatcher/1.1.5.json
=> Trading Post Watcher Release v1.1.5

manifests/estreya/bh/liveMap/1.2.4.json
=> Live Map Release v1.2.4

manifests/com/shooper/ddr/1.4.0.json
=> Dance Dance Rotation Release v1.4.0

manifests/estreya/bh/eventTable/3.10.0.json
=> Event Table Release v3.10.0

manifests/ecksofa/sessiontracker/9.0.0.json
=> Session Tracker Release v9.0.0

manifests/fs/nexusshim/0.0.2.json
=> Nexus Shim Release v0.0.2

manifests/Ideka/CustomCombatText/0.2.1.json
=> Custom Combat Text Release v0.2.1

manifests/fs/nexusshim/0.0.4.json
=> Nexus Shim Release v0.0.4

manifests/estreya/bh/eventTable/3.11.0.json
=> Event Table Release v3.11.0

manifests/estreya/bh/liveMap/1.2.5.json
=> Live Map Release v1.2.5

manifests/Ideka/CustomCombatText/0.2.2.json
=> Custom Combat Text Release v0.2.2

manifests/Nekres/Chat_Shorts/0.15.0.json
=> Chat Shorts Release v0.15.0

manifests/ecksofa/sessiontracker/10.0.0.json
=> Session Tracker Release v10.0.0

manifests/estreya/bh/eventTable/3.12.0.json
=> Event Table Release v3.12.0

manifests/estreya/bh/startupNotifications/0.1.0.json
=> Startup Notifications Release v0.1.0

manifests/Nekres/Music_Mixer/1.1.13.json
=> Mount Music Release v1.1.13

manifests/com/shooper/ddr/1.5.0.json
=> Dance Dance Rotation Release v1.5.0

manifests/Nekres/FailScreens/0.4.0.json
=> Fail Screens Release v0.4.0

manifests/Nekres/Chat_Shorts/0.15.1.json
=> Chat Shorts Release v0.15.1

manifests/bh/community/pathing/1.6.5.json
=> Pathing Release v1.6.5

manifests/Nekres/WindowResize/0.2.1.json
=> GW2 Window Resizer Release v0.2.1

manifests/bh/community/pathing/1.6.6.json
=> Pathing Release v1.6.6

manifests/Nekres/FailScreens/0.5.0.json
=> Fail Screens Release v0.5.0

manifests/Taimi/EnterTheSandstorm/0.1.0.json
SSRD Build Triggered by Tiny Taimi
=> Enter The Sandstorm Release v0.1.0

manifests/com/shooper/ddr/1.5.1.json
=> Dance Dance Rotation Release v1.5.1

manifests/Ideka/CustomCombatText/0.2.3.json
=> Custom Combat Text Release v0.2.3

manifests/Ideka/HitboxView/1.2.1.json
=> Hitbox View Release v1.2.1

manifests/Ideka/HitboxView/1.2.2.json
=> Hitbox View Release v1.2.2

manifests/Nekres/Chat_Shorts/0.15.3.json
=> Chat Shorts Release v0.15.3

manifests/KillProofModule/2.21.6.json
=> Proof Logix Release v2.21.6

manifests/Nekres/Music_Mixer/1.1.16.json
=> Mount Music Release v1.1.16

manifests/Nekres/FailScreens/0.6.1.json
=> Fail Screens Release v0.6.1

manifests/Nekres/FailScreens/0.7.0.json
=> Fail Screens Release v0.7.0

manifests/Nekres/Regions_Of_Tyria/0.12.5.json
=> Regions of Tyria Release v0.12.5

manifests/estreya/bh/eventTable/3.13.0.json
=> Event Table Release v3.13.0

manifests/Ideka/CustomCombatText/1.0.0.json
=> Custom Combat Text Release v1.0.0

manifests/bh/community/pathing/1.7.3.json
=> Pathing Release v1.7.3

manifests/Nekres/FailScreens/0.8.0.json
=> Fail Screens Release v0.8.0

manifests/Ideka/CustomCombatText/1.1.0-beta.json
=> Custom Combat Text Release v1.1.0-beta

manifests/bh/community/pathing/1.7.5.json
=> Pathing Release v1.7.5

manifests/com/shooper/ddr/1.5.2.json
=> Dance Dance Rotation Release v1.5.2

manifests/Ideka/CustomCombatText/1.2.0-beta.json
=> Custom Combat Text Release v1.2.0-beta

manifests/Soeed/RaidClears/3.0.0.json
=> Clears Tracker Release v3.0.0

manifests/Kenedia/Modules/Characters/1.0.25.json
=> Characters Release v1.0.25

manifests/Kiroho/Joka/EmoteTome/1.1.2.json
=> EmoteTome Release v1.1.2

manifests/Nekres/Musician_Module/0.8.5.json
=> Minstrel Protocol Release v0.8.5

manifests/Ideka/CustomCombatText/1.3.0.json
=> Custom Combat Text Release v1.3.0

manifests/Ideka/CustomCombatText/1.4.0.json
=> Custom Combat Text Release v1.4.0

manifests/KillProofModule/2.21.7.json
=> Proof Logix Release v2.21.7

manifests/KillProofModule/2.22.1.json
=> Proof Logix Release v2.22.1

manifests/KillProofModule/2.22.4.json
=> Proof Logix Release v2.22.4

manifests/KillProofModule/2.22.5.json
=> Proof Logix Release v2.22.5

manifests/KillProofModule/2.22.6.json
=> Proof Logix Release v2.22.6

manifests/Nekres/Music_Mixer/1.2.0.json
=> Mount Music Release v1.2.0

manifests/estreya/bh/eventTable/3.14.0.json
=> Event Table Release v3.14.0

manifests/Nekres/Music_Mixer/1.2.2.json
=> Mount Music Release v1.2.2

manifests/Nekres/Regions_Of_Tyria/0.13.2.json
=> Regions of Tyria Release v0.13.2

manifests/Nekres/Music_Mixer/1.2.3.json
=> Mount Music Release v1.2.3

manifests/Nekres/Music_Mixer/1.2.4.json
=> Mount Music Release v1.2.4

manifests/Nekres/Regions_Of_Tyria/0.13.5.json
=> Regions of Tyria Release v0.13.5

manifests/Nekres/Regions_Of_Tyria/0.13.6.json
=> Regions of Tyria Release v0.13.6

manifests/Nekres/Music_Mixer/1.2.5.json
=> Mount Music Release v1.2.5

manifests/Nekres/Music_Mixer/1.2.6.json
=> Mount Music Release v1.2.6

manifests/Ideka/RacingMeter/1.9.3.json
=> Racing Meter Release v1.9.3

manifests/Nekres/Music_Mixer/1.4.0.json
=> Mount Music Release v1.4.0

manifests/fs/bagofholding/1.0.0.json
=> Bag of Holding Release v1.0.0

manifests/ecksofa/farmingtracker/1.0.0.json
=> Farming Tracker Release v1.0.0

manifests/japyx/kprefresher/1.5.4.json
=> KpRefresher Release v1.5.4

manifests/Kiroho/Joka/EmoteTome/1.1.3.json
=> EmoteTome Release v1.1.3

manifests/Kiroho/Joka/EmoteTome/1.1.4.json
=> EmoteTome Release v1.1.4

manifests/MysticCrafting/Module/1.3.1.json
=> Mystic Crafting Release v1.3.1

manifests/Nekres/Music_Mixer/1.6.0.json
=> Mount Music Release v1.6.0

manifests/Denrage/AchievementTrackerModule/0.1.10.json
=> Achievement Tracker Release v0.1.10

manifests/Nekres/Music_Mixer/1.6.2.json
=> Mount Music Release v1.6.2

manifests/bh/community/pathing/1.8.5.json
=> Pathing Release v1.8.5

manifests/Nekres/Chat_Shorts/0.15.8.json
=> Chat Shorts Release v0.15.8

manifests/Kiroho/Joka/EmoteTome/1.1.6.json
=> EmoteTome Release v1.1.6

manifests/MysticCrafting/Module/1.3.2.json
=> Mystic Crafting Release v1.3.2

manifests/Manlaan/Mounts/1.4.11.json
=> Mounts & More Release v1.4.11

manifests/Nekres/Chat_Shorts/0.15.9.json
=> Chat Shorts Release v0.15.9

manifests/Manlaan/Mounts/1.4.12.json
=> Mounts & More Release v1.4.12

manifests/Manlaan/CommanderMarkers/3.3.1.json
=> Commander Markers Release v3.3.1

manifests/japyx/kprefresher/1.5.5.json
=> KpRefresher Release v1.5.5

manifests/bh/community/pathing/1.8.6.json
=> Pathing Release v1.8.6

manifests/Nekres/Chat_Shorts/0.15.11.json
=> Chat Shorts Release v0.15.11

manifests/Nekres/Music_Mixer/1.7.0.json
=> Mount Music Release v1.7.0

manifests/Nekres/Music_Mixer/1.7.4.json
=> Mount Music Release v1.7.4

manifests/japyx/kprefresher/1.6.0.json
=> KpRefresher Release v1.6.0

manifests/Nekres/Music_Mixer/1.7.5.json
=> Mount Music Release v1.7.5

manifests/KillProofModule/2.22.9.json
=> Proof Logix Release v2.22.9

manifests/Nekres/Chat_Shorts/0.15.14.json
=> Chat Shorts Release v0.15.14

manifests/Ideka/RacingMeter/1.10.0.json
=> Racing Meter Release v1.10.0

manifests/Ideka/CustomCombatText/1.4.1.json
=> Custom Combat Text Release v1.4.1

manifests/Manlaan/Mounts/1.4.13.json
=> Mounts & More Release v1.4.13

manifests/ecksofa/farmingtracker/2.0.0.json
=> Farming Tracker Release v2.0.0

manifests/KillProofModule/2.22.10.json
=> Proof Logix Release v2.22.10

manifests/KillProofModule/2.22.11.json
=> Proof Logix Release v2.22.11

manifests/KillProofModule/2.22.15.json
=> Proof Logix Release v2.22.15

manifests/ecksofa/farmingtracker/3.0.0.json
=> Farming Tracker Release v3.0.0

manifests/Kenedia/Modules/QoL/1.0.7.json
=> Tyrian QoL Release v1.0.7

manifests/Ideka/RacingMeter/1.10.1.json
=> Racing Meter Release v1.10.1

manifests/Ideka/HitboxView/1.2.3.json
=> Hitbox View Release v1.2.3

manifests/Ideka/CustomCombatText/1.4.2.json
=> Custom Combat Text Release v1.4.2

manifests/MysticCrafting/Module/1.4.0.json
=> Mystic Crafting Release v1.4.0

manifests/bh/community/pathing/1.8.7.json
=> Pathing Release v1.8.7

manifests/flakysalt/CharacterKeybinds/1.0.0.json
SSRD Build Triggered by flakysalt
=> Character Keybinds Release v1.0.0

manifests/estreya/bh/eventTable/3.15.0.json
=> Event Table Release v3.15.0

manifests/bh/community/pathing/1.8.8.json
=> Pathing Release v1.8.8

manifests/estreya/bh/liveMap/1.2.6.json
=> Live Map Release v1.2.6

manifests/Manlaan/Mounts/1.5.0.json
=> Mounts & More Release v1.5.0

manifests/ecksofa/farmingtracker/4.0.0.json
=> Farming Tracker Release v4.0.0

manifests/Nekres/Mumble_Info/0.4.0.json
=> Mumble Info Release v0.4.0

manifests/Nekres/Mumble_Info/0.4.1.json
=> Mumble Info Release v0.4.1

manifests/Nekres/Mumble_Info/0.4.4.json
=> Mumble Info Release v0.4.4

manifests/Kenedia/Modules/BuildsManager/1.0.1.json
=> Builds Manager Release v1.0.1

manifests/Kenedia/Modules/BuildsManager/1.0.2.json
=> Builds Manager Release v1.0.2

manifests/Kenedia/Modules/BuildsManager/1.0.3.json
=> Builds Manager Release v1.0.3

manifests/MysticCrafting/Module/1.4.1.json
=> Mystic Crafting Release v1.4.1

manifests/flakysalt/CharacterKeybinds/1.1.0.json
SSRD Build Triggered by flakysalt
=> Character Keybinds Release v1.1.0

manifests/Manlaan/Mounts/1.5.1.json
=> Mounts & More Release v1.5.1

manifests/Kiroho/Joka/EmoteTome/1.1.8.json
=> EmoteTome Release v1.1.8

manifests/Kenedia/Modules/BuildsManager/1.0.5.json
=> Builds Manager Release v1.0.5

manifests/ecksofa/farmingtracker/5.0.0.json
=> Farming Tracker Release v5.0.0

manifests/Kenedia/Modules/BuildsManager/1.0.6.json
=> Builds Manager Release v1.0.6

manifests/Kenedia/Modules/BuildsManager/1.0.7.json
=> Builds Manager Release v1.0.7

manifests/japyx/kprefresher/1.7.0.json
=> KpRefresher Release v1.7.0

manifests/xyz/f3l1x/blishemotes/1.3.1.json
=> Emotes Release v1.3.1

manifests/Kenedia/Modules/BuildsManager/1.0.8.json
=> Builds Manager Release v1.0.8

manifests/Nekres/Music_Mixer/1.8.1.json
=> Mount Music Release v1.8.1

manifests/Nekres/FailScreens/0.10.0.json
=> Fail Screens Release v0.10.0

manifests/MysticCrafting/Module/1.5.0.json
=> Mystic Crafting Release v1.5.0

manifests/MysticCrafting/Module/1.5.1.json
=> Mystic Crafting Release v1.5.1

manifests/Nekres/Mistwar/1.4.9.json
=> Mistwar Release v1.4.9

manifests/japyx/kprefresher/1.7.1.json
=> KpRefresher Release v1.7.1

manifests/Soeed/RaidClears/3.1.0.json
=> Clears Tracker Release v3.1.0

manifests/Soeed/RaidClears/3.1.1.json
=> Clears Tracker Release v3.1.1

manifests/Kenedia/Modules/BuildsManager/1.0.9.json
=> Builds Manager Release v1.0.9

manifests/com/shooper/ddr/1.6.0.json
=> Dance Dance Rotation Release v1.6.0

manifests/xyz/f3l1x/blishemotes/1.3.2.json
=> Emotes Release v1.3.2

manifests/Soeed/RaidClears/3.2.0.json
=> Clears Tracker Release v3.2.0

manifests/bh/decor/decormodule/1.2.0.json
=> Decor Release v1.2.0

manifests/bh/decor/decormodule/1.2.2.json
=> Decor Release v1.2.2

manifests/bh/decor/decormodule/1.2.4.json
=> Decor Release v1.2.4

manifests/Kiroho/Joka/EmoteTome/1.2.1.json
=> EmoteTome Release v1.2.1

manifests/MysticCrafting/Module/1.5.2.json
=> Mystic Crafting Release v1.5.2

manifests/bh/decor/decormodule/1.2.5.json
=> Decor Release v1.2.5

manifests/bh/decor/decormodule/1.2.6.json
=> Decor Release v1.2.6

manifests/MysticCrafting/Module/1.5.3.json
=> Mystic Crafting Release v1.5.3

manifests/sliekens/chat_links/1.0.0.json
=> Chat Links Release v1.0.0

manifests/sliekens/chat_links/1.0.1.json
=> Chat Links Release v1.0.1

manifests/bh/general/events/1.0.3.json
=> Events and Metas Observer Release v1.0.3

manifests/japyx/kprefresher/1.7.3.json
=> KpRefresher Release v1.7.3

manifests/xyz/f3l1x/blishemotes/1.3.3.json
=> Emotes Release v1.3.3

manifests/Ideka/RacingMeter/1.10.2.json
=> Racing Meter Release v1.10.2

manifests/sliekens/chat_links/2.0.0.json
=> Chat Links Release v2.0.0

manifests/bh/decor/decormodule/1.3.0.json
=> Decor Release v1.3.0

manifests/japyx/drmtracker/1.0.0.json
=> DrmTracker Release v1.0.0

manifests/japyx/drmtracker/1.1.0.json
=> DrmTracker Release v1.1.0

manifests/Nekres/Music_Mixer/1.9.0.json
=> Mount Music Release v1.9.0

manifests/bh/decor/decormodule/1.3.1.json
=> Decor Release v1.3.1

manifests/Nekres/Music_Mixer/1.9.5.json
=> Mount Music Release v1.9.5

manifests/Nekres/Music_Mixer/1.9.6.json
=> Mount Music Release v1.9.6

manifests/Nekres/Music_Mixer/1.9.7.json
=> Mount Music Release v1.9.7

manifests/Nekres/Music_Mixer/1.9.10.json
=> Mount Music Release v1.9.10

manifests/Nekres/Music_Mixer/1.9.11.json
=> Mount Music Release v1.9.11

manifests/bh/decor/decormodule/1.4.1.json
=> Decor Release v1.4.1

manifests/bh/decor/decormodule/1.4.2.json
=> Decor Release v1.4.2

manifests/com/shooper/ddr/1.7.0.json
=> Dance Dance Rotation Release v1.7.0

manifests/bh/decor/decormodule/1.4.3.json
=> Decor Release v1.4.3

manifests/Manlaan/Mounts/1.5.2.json
=> Mounts & More Release v1.5.2

manifests/Kenedia/Modules/Characters/1.0.27.json
=> Characters Release v1.0.27

manifests/bh/community/pathing/1.9.0.json
=> Pathing Release v1.9.0

manifests/Nekres/Chat_Shorts/0.15.16.json
=> Chat Shorts Release v0.15.16

manifests/sliekens/chat_links/3.0.0.json
=> Chat Links Release v3.0.0

manifests/sliekens/chat_links/3.0.1.json
=> Chat Links Release v3.0.1

manifests/bh/decor/decormodule/1.4.6.json
=> Decor Release v1.4.6

manifests/sliekens/chat_links/3.0.2.json
=> Chat Links Release v3.0.2

manifests/sliekens/chat_links/4.0.0.json
=> Chat Links Release v4.0.0

manifests/sliekens/chat_links/4.1.0.json
=> Chat Links Release v4.1.0

manifests/Ideka/RacingMeter/1.11.0.json
=> Racing Meter Release v1.11.0

manifests/Ideka/CustomCombatText/1.5.0.json
=> Custom Combat Text Release v1.5.0

manifests/sliekens/chat_links/4.1.1.json
=> Chat Links Release v4.1.1

manifests/Denrage/AchievementTrackerModule/0.1.11.json
=> Achievement Tracker Release v0.1.11

manifests/sliekens/chat_links/5.0.0.json
=> Chat Links Release v5.0.0

manifests/Kiroho/Joka/EmoteTome/1.3.0.json
=> EmoteTome Release v1.3.0

manifests/Ideka/CustomCombatText/1.5.1.json
=> Custom Combat Text Release v1.5.1

manifests/gw2stacks_blish/0.1.3.json
SSRD Build Triggered by ImDarla
=> gw2stacks: Blish edition Release v0.1.3

manifests/sliekens/chat_links/5.1.0.json
=> Chat Links Release v5.1.0

manifests/gw2stacks_blish/0.1.4.json
SSRD Build Triggered by ImDarla
=> gw2stacks: Blish edition Release v0.1.4

manifests/estreya/bh/eventTable/3.16.1.json
=> Event Table Release v3.16.1

manifests/estreya/bh/liveMap/1.3.0.json
=> Live Map Release v1.3.0

manifests/sliekens/chat_links/5.2.0.json
=> Chat Links Release v5.2.0

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.1.1.json
=> Fishing Buddy Release v1.1.1

manifests/Manlaan/MouseCursor/2.3.0.json
SSRD Build Triggered by phiphire
=> Mouse Cursor Release v2.3.0

manifests/Nekres/Music_Mixer/1.9.12.json
=> Mount Music Release v1.9.12

manifests/com/shooper/ddr/1.7.1.json
=> Dance Dance Rotation Release v1.7.1

manifests/sliekens/chat_links/5.3.0.json
=> Chat Links Release v5.3.0

manifests/Nekres/Music_Mixer/1.9.13.json
=> Mount Music Release v1.9.13

manifests/gw2stacks_blish/0.1.5.json
SSRD Build Triggered by ImDarla
=> gw2stacks: Blish edition Release v0.1.5

manifests/Kiroho/Joka/EmoteTome/1.3.1.json
=> EmoteTome Release v1.3.1

manifests/xyz/f3l1x/blishemotes/1.3.4.json
=> Emotes Release v1.3.4

manifests/estreya/bh/eventTable/3.16.2.json
=> Event Table Release v3.16.2

manifests/estreya/bh/liveMap/1.3.1.json
=> Live Map Release v1.3.1

manifests/Soeed/TargetYourFeet/1.1.1.json
=> Bomb your feet Release v1.1.1

manifests/bh/decor/decormodule/1.4.9.json
=> Decor Release v1.4.9

manifests/sliekens/chat_links/5.4.0.json
=> Chat Links Release v5.4.0

manifests/Ideka/CustomCombatText/1.6.0.json
=> Custom Combat Text Release v1.6.0

manifests/MysticCrafting/Module/1.5.4.json
=> Mystic Crafting Release v1.5.4

manifests/MysticCrafting/Module/1.5.5.json
=> Mystic Crafting Release v1.5.5

manifests/sliekens/chat_links/5.4.1.json
=> Chat Links Release v5.4.1

manifests/bh/general/events/1.0.4.json
=> Events and Metas Observer Release v1.0.4

manifests/Kenedia/Modules/Characters/1.0.29.json
=> Characters Release v1.0.29

manifests/Kenedia/Modules/QoL/1.0.9.json
=> Tyrian QoL Release v1.0.9

manifests/bh/general/events/1.0.5.json
=> Events and Metas Observer Release v1.0.5

manifests/Kenedia/Modules/QoL/1.0.10.json
=> Tyrian QoL Release v1.0.10

manifests/sliekens/chat_links/5.4.2.json
=> Chat Links Release v5.4.2

manifests/bh/general/events/1.0.6.json
=> Events and Metas Observer Release v1.0.6

manifests/MysticCrafting/Module/1.5.7.json
=> Mystic Crafting Release v1.5.7

manifests/Soeed/GuildGeoGuesser/0.8.0.json
=> Guild Geo Guesser Release v0.8.0

manifests/bh/community/pathing/1.10.7.json
=> Pathing Release v1.10.7

manifests/Kiroho/Joka/EmoteTome/1.3.2.json
=> EmoteTome Release v1.3.2

manifests/Nekres/Screenshot_Manager/0.6.1.json
=> Screenshot Manager Release v0.6.1

manifests/Kenedia/Modules/BuildsManager/1.0.10.json
=> Builds Manager Release v1.0.10

manifests/Kenedia/Modules/Characters/1.0.30.json
=> Characters Release v1.0.30

manifests/Kenedia/Modules/Characters/1.0.33.json
=> Characters Release v1.0.33

manifests/Kenedia/Modules/Characters/1.0.34.json
=> Characters Release v1.0.34

manifests/Kenedia/Modules/BuildsManager/1.0.11.json
=> Builds Manager Release v1.0.11

manifests/bh/community/pathing/1.10.8.json
=> Pathing Release v1.10.8

manifests/falcon/cmtracker/1.2.1.json
SSRD Build Triggered by Falcon
=> CM Tracker Release v1.2.1

manifests/Nekres/Mistwar/1.4.10.json
=> Mistwar Release v1.4.10
