blish-hud/bhud-pkgs

manifests/KillProofModule/1.5.3.json
manifests/KillProofModule/1.5.5.json
manifests/Nekres/KillProof/1.3.0.json
manifests/Nekres/KillProof/1.4.3.json
manifests/Nekres/KillProof/1.4.4.json
manifests/Nekres/KillProof/1.4.5.json
manifests/Nekres/KillProof/1.5.0.json
manifests/Nekres/KillProof/1.5.1.json

Both KillProof namespaces for testing.

KillProof Init

---

manifests/Nekres/Mumble_Info_Module/0.2.0.json
manifests/Nekres/Mumble_Info_Module/0.2.1.json
manifests/Nekres/Mumble_Info_Module/0.2.2.json

Display colorized mumble and process info on the screen using a toggle key. (Default F7)

:tada: Add Mumble Info v0.2.0

---

manifests/Nekres/Mumble_Info_Module/0.2.3.json

Add default key and compass direction.

:sparkles: Add Mumble Info v.0.2.3

---

manifests/Nekres/Quick_Surrender_Module/0.1.2.json
manifests/Nekres/Quick_Surrender_Module/0.1.3.json
manifests/Nekres/Quick_Surrender_Module/0.1.4.json
manifests/Nekres/Random_Generator_Module/0.1.1.json
manifests/Nekres/Random_Generator_Module/0.1.3.json

Both are very tiny and very similar. Hence why I PR them simultainiously. Since they are very tiny they are perfect to test the library once its out.
I cleaned the code. Both work flawlessly.
~~However, they require ``GameIntegration.IsInGameChanged`` as an event from the latest commit in [PR#333](https://github.com/blish-hud/Blish-HUD/pull/333) to be merged. Since I am under time constraints I will assume it is going to be merged as it was approved before. (I am trying to get as many modules out as I can before the next week.)~~ ✅ 
Source of Quick Surrender: https://github.com/TybaIt/Blish-HUD-Modules/tree/master/Quick%20Surrender%20Module
Source of Random Generator: https://github.com/TybaIt/Blish-HUD-Modules/tree/master/Random%20Generator%20Module

QuickSurrender v0.1.2 and RandomGenerator v0.1.1

---

manifests/Nekres/Mumble_Info_Module/0.2.4.json

Add interface-relative cursor position.

:sparkles: Add Mumble Info v0.2.4

---

manifests/Taimi/UndaDaSea_BlishHUD/1.0.1.json

🦀🧜‍♀️ Take your Guild Wars 2 underwater combat to a whole new level, down where its wetter!

UndaDaSea 1.0.1

---

manifests/Nekres/Regions_Of_Tyria/0.2.1.json

🎉 Add *Regions of Tyria* v0.2.1
"*Shows the name of the place you are entering.*"

🎉 Regions of Tyria v0.2.1

---

manifests/Manlaan/Clock/1.0.0.json
manifests/Manlaan/DistanceRings/1.0.0.json
manifests/Manlaan/MouseCursor/1.0.0.json

MouseCursor 1.0.0
DistanceRings 1.0.0
Clock 1.0.0

Add 3 Modules

---

manifests/Manlaan/Clock/1.0.1.json

Just a minor fix.
Fixed Settings to display Font Size correctly.
Updated Blish Reference to 0.7.0

Clock 1.0.1

---

manifests/Manlaan/MouseCursor/1.0.1.json

Added Setting to hide on Camera Drag. from Nekros
Updated Blish Reference to 0.7.0

MouseCursor 1.0.1

---

manifests/Manlaan/DistanceRings/1.0.2.json

DistanceRings 1.0.2

---

manifests/Manlaan/MouseCursor/1.0.2.json

Fix mouse cursor moving when entering window and first action is holding right click.

MouseCursor 1.0.2

---

manifests/Manlaan/MouseCursor/1.0.3.json

MouseCursor 1.0.3

---

manifests/Manlaan/Clock/1.0.3.json

Clock 1.0.3

---

manifests/Manlaan/HPGrid/1.0.3.json

HPGrid 1.0.3

---

manifests/Manlaan/Mounts/1.0.0.json

Mounts 1.0.0

---

manifests/Manlaan/CommanderMarkers/1.0.0.json

CommanderMarkers 1.0.0

---

manifests/Nekres/Regions_Of_Tyria/0.3.5.json

[Source Code](https://github.com/agaertner/Blish-HUD-Modules/tree/master/Regions%20Of%20Tyria%20Module)

Add Regions of Tyria 0.3.5

---

manifests/entrhopi/Guild-Missions/0.2.1.json

Treks can now be saved to a list which is automatically sorted by map.

Guild Missions 0.2.1

---

manifests/Manlaan/Mounts/1.0.1.json

Mounts 1.0.1

---

manifests/Manlaan/HPGrid/1.0.4.json

HPGrid 1.0.4

---

manifests/Manlaan/MouseCursor/1.0.5.json

MouseCursor 1.0.5

---

manifests/Manlaan/Clock/1.0.4.json

New Settings: 24H time, Label/Time alignment, Hiding Labels.

Clock 1.0.4

---

manifests/Manlaan/Clock/1.0.5.json

Fix for Blish 0.10.0-156 Mouse/Window Handling.

Clock 1.0.5

---

manifests/Manlaan/Clock/1.1.0.json

Clock 1.1.0

---

manifests/Manlaan/DistanceRings/1.1.0.json

DistanceRings 1.1.0

---

manifests/Nekres/Regions_Of_Tyria/0.5.1.json
manifests/Nekres/Stream_Out_Module/0.2.1.json

Region of Tyria v0.5.1
- Fix crash when API is unavailable.
Stream Out v0.2.1
- Add SPvP/WvW kills and deaths weekly/daily

Update Stream out v0.2.1 and Regions of Tyria v0.5.1

---

manifests/Nekres/Stream_Out/0.4.1.json

- Add pvp_win_loss_ratio.txt
- Add WvW rank
- Fix no pvp rank output if no active season. Now looks for most recent season.
- Fix font clipping for high DPI
- Fix white flickering

add Stream Out v0.4.1

---

manifests/Manlaan/Mounts/1.1.0.json

Upgraded to use Blish 0.11
Moved images to be in a panel
Added option to drag panel instead of typing in coords.
Separated corner and manual icons into own functions
Added a custom Settings View

Mounts 1.1.0

---

manifests/Manlaan/CommanderMarkers/1.1.0.json

Upgraded to use Blish 0.11
Moved images to be in a panel
Added option to drag panel instead of typing in coords.
Added a custom Settings View

CommanderMarkers 1.1.0

---

manifests/Taimi/UndaDaSea_BlishHUD/2.0.0.json

✅ Blish HUD v0.11.1+ Support
✅ Switched audio to NAudio
✅ Performance Improvements

UndaDaSea v2.0.0

---

manifests/bh/community/pathing/0.13.9.json

- Fixed the positioning of the settings hint icon.

Pathing v0.13.9

---

manifests/Nekres/Regions_Of_Tyria/0.5.3.json

- disable sector detection in competitive modes

Regions of Tyria v0.5.3

---

manifests/Nekres/Stream_Out/0.4.9.json

Fix detecting one tier short off current one in some cases.

fix rank/tier icon generation

---

manifests/Nekres/Stream_Out/0.5.2.json

clear guild emblem if guild has no emblem

---

manifests/Nekres/Stream_Out/0.5.3.json

Fix guild emblems clipping. Assert for API returning layers of different sizes.

assert guild emblem layer sizes and scale

---

manifests/Manlaan/MouseCursor/2.1.4.json
manifests/Manlaan/MouseCursor/2.2.0.json

Added Only Combat option
Updated for Blish 0.11.4

MouseCursor 2.2.0

---

manifests/Manlaan/Mounts/1.2.2.json

Mounts 1.2.2

---

manifests/Manlaan/Mounts/1.2.7.json

Added Behaviors for Radial/Default + Center Radial: None, Default, LastUsed
Made settings icon grey + fix bug with mount queuring
Added customizations, moved settings
Add radial
Add turtle mount

Mounts 1.2.7

---

manifests/Manlaan/Mounts/1.2.12.json

Mounts 1.2.12

---

manifests/bh/general/events/0.9.1.json

SSRD Build Triggered by FreesnÃ¶w

Events and Metas Observer Release v0.9.1

---

manifests/bh/general/universalsearch/0.7.0.json

SSRD Build Triggered by FreesnÃ¶w

Universal Search Release v0.7.0

---

manifests/estreya/bh/eventTable/1.3.0.json

Event Table Release v1.3.0

---

manifests/estreya/bh/eventTable/1.3.2.json

Event Table Release v1.3.2

---

manifests/Manlaan/Clock/1.1.0.json
manifests/Manlaan/Clock/1.1.1.json
manifests/Manlaan/Clock/1.1.2.json

Fix placement bug
Blish 0.11.6

Clock 1.1.2

---

manifests/Snaid1/Blishpad/1.0.2.json

Blishpad Release v1.0.2

---

manifests/estreya/bh/eventTable/1.4.0.json

Event Table Release v1.4.0

---

manifests/Nekres/Stream_Out/0.5.7.json

Stream Out Release v0.5.7

---

manifests/Snaid1/Blishpad/1.0.3.json

Blishpad Release v1.0.3

---

manifests/estreya/bh/eventTable/1.4.2.json

Event Table Release v1.4.2

---

manifests/Nekres/Screenshot_Manager/0.3.5.json

Screenshot Manager Release v0.3.5

---

manifests/Snaid1/Blishpad/1.1.1.json

Blishpad Release v1.1.1

---

manifests/Nekres/Screenshot_Manager/0.3.7.json

Screenshot Manager Release v0.3.7

---

manifests/Snaid1/Blishpad/1.1.2.json

Blishpad Release v1.1.2

---

manifests/bh/community/pathing/0.17.6.json

Pathing Release v0.17.6

---

manifests/Nekres/Screenshot_Manager/0.3.8.json

Screenshot Manager Release v0.3.8

---

manifests/Snaid1/Blishpad/1.1.3.json

Blishpad Release v1.1.3

---

manifests/GW2Characters/0.1.3.json

GW2Characters Release v0.1.3

---

manifests/Nekres/Screenshot_Manager/0.3.9.json

Screenshot Manager Release v0.3.9

---

manifests/Manlaan/HPGrid/1.0.5.json

Add EOD tags
Lots of Cleanup
Thanks QuitarHero
Blish 0.11.6

HPGrid 1.0.5

---

manifests/bh/general/events/0.9.2.json

Events and Metas Observer Release v0.9.2

---

manifests/entrhopi/Guild_Missions/1.5.2.json

Spanish translation thanks to Zabb

Guild_Missions 1.5.2

---

manifests/Nekres/Mumble_Info/0.2.9.json

Mumble Info Release v0.2.9

---

manifests/Nekres/Inquest_Module/0.1.8.json

Inquest Chipset Release v0.1.8

---

manifests/Nekres/Inquest_Module/0.1.9.json

Inquest Chipset Release v0.1.9

---

manifests/Kenedia/Modules/Characters/0.1.4.json

Characters Release v0.1.4

---

manifests/bh/community/pathing/0.18.1.json

Pathing Release v0.18.1

---

manifests/Nekres/Inquest_Module/0.2.4.json

Inquest Chipset Release v0.2.4

---

manifests/bh/community/pathing/0.18.2.json

Pathing Release v0.18.2

---

manifests/Kenedia/Modules/Characters/0.1.8.json

Characters Release v0.1.8

---

manifests/Nekres/Screenshot_Manager/0.4.3.json

Screenshot Manager Release v0.4.3

---

manifests/Nekres/Inquest_Module/0.2.6.json

Inquest Chipset Release v0.2.6

---

manifests/Nekres/Inquest_Module/0.3.0.json

Inquest Chipset Release v0.3.0

---

manifests/Kenedia/Modules/Characters/0.1.9.json

Characters Release v0.1.9

---

manifests/Nekres/Screenshot_Manager/0.4.4.json

Screenshot Manager Release v0.4.4

---

manifests/bh/community/pathing/0.18.4.json

Pathing Release v0.18.4

---

manifests/Nekres/Inquest_Module/0.3.4.json

Inquest Chipset Release v0.3.4

---

manifests/Nekres/Screenshot_Manager/0.4.5.json

Screenshot Manager Release v0.4.5

---

manifests/Nekres/Inquest_Module/0.3.6.json

Inquest Chipset Release v0.3.6

---

manifests/Nekres/Regions_Of_Tyria/0.5.7.json

Regions of Tyria Release v0.5.7

---

manifests/Nekres/Stream_Out/0.5.8.json

Stream Out Release v0.5.8

---

manifests/Nekres/Mistwar/0.4.4.json

Mistwar Release v0.4.4

---

manifests/Nekres/Notes/0.5.0.json

Commander's Quire (Journal) Release v0.5.0

---

manifests/bh/community/pathing/0.18.5.json

Pathing Release v0.18.5

---

manifests/Nekres/Regions_Of_Tyria/0.5.8.json

Regions of Tyria Release v0.5.8

---

manifests/Nekres/Mistwar/0.4.5.json

Mistwar Release v0.4.5

---

manifests/bh/community/pathing/0.18.7.json

Pathing Release v0.18.7

---

manifests/Nekres/Stopwatch/0.1.9.json

Stopwatch Release v0.1.9

---

manifests/bh/community/pathing/0.18.8.json

Pathing Release v0.18.8

---

manifests/Nekres/Screenshot_Manager/0.4.6.json

Screenshot Manager Release v0.4.6

---

manifests/Torlando/SquadTracker/0.2.2.json

SSRD Build Triggered by Torlando

Squad Tracker Release v0.2.2

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.3.json

FishingBuddy Release v1.0.3

---

manifests/Nekres/Inquest_Module/0.3.8.json

Inquest Chipset Release v0.3.8

---

manifests/Kenedia/Modules/Characters/0.2.6.json

Characters Release v0.2.6

---

manifests/Kenedia/Modules/Characters/0.2.7.json

Characters Release v0.2.7

---

manifests/estreya/bh/eventTable/1.5.0.json

Event Table Release v1.5.0

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.4.json

Fishing Buddy Release v1.0.4

---

manifests/Kenedia/Modules/Characters/0.2.8.json

Characters Release v0.2.8

---

manifests/estreya/bh/eventTable/1.5.1.json

Event Table Release v1.5.1

---

manifests/Nekres/Stream_Out/0.6.1.json

Stream Out Release v0.6.1

---

manifests/Nekres/Musician_Module/0.6.4.json

Musician Release v0.6.4

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.5.json

Fishing Buddy Release v1.0.5

---

manifests/Nekres/Musician_Module/0.6.5.json

Musician Release v0.6.5

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.6.json

Fishing Buddy Release v1.0.6

---

manifests/bh/community/pathing/0.18.9.json

Pathing Release v0.18.9

---

manifests/ecksofa/gatheringtools/1.0.0.json

Gathering Tools Release v1.0.0

---

manifests/ecksofa/gatheringtools/1.0.1.json

Gathering Tools Release v1.0.1

---

manifests/Nekres/Musician_Module/0.8.1.json

Musician Release v0.8.1

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.7.json

Fishing Buddy Release v1.0.7

---

manifests/bh/community/pathing/0.18.11.json

Pathing Release v0.18.11

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.8.json

Fishing Buddy Release v1.0.8

---

manifests/bh/community/pathing/0.18.13.json

Pathing Release v0.18.13

---

manifests/bh/general/universalsearch/0.7.1.json

Universal Search Release v0.7.1

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.9.json

Fishing Buddy Release v1.0.9

---

manifests/ecksofa/gatheringtools/1.1.0.json

Gathering Tools Release v1.1.0

---

manifests/Nekres/Musician_Module/0.8.2.json

Minstrel Protocol Release v0.8.2

---

manifests/Charr/Timers_BlishHUD/0.3.10.json

Timers Release v0.3.10

---

manifests/Nekres/Chat_Shorts/0.1.3.json

Chat Shorts Release v0.1.3

---

manifests/bh/community/pathing/0.18.15.json

Pathing Release v0.18.15

---

manifests/bh/community/pathing/0.18.16.json

Pathing Release v0.18.16

---

manifests/estreya/bh/eventTable/1.6.0.json

Event Table Release v1.6.0

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.10.json

Fishing Buddy Release v1.0.10

---

manifests/pentose/itemsearch/0.3.0.json

Item Search Release v0.3.0

---

manifests/Ideka/MistsQuill/1.1.0.json

Quill of the Mists Release v1.1.0

---

manifests/estreya/bh/eventTable/1.7.0.json

Event Table Release v1.7.0

---

manifests/ecksofa/gatheringtools/1.1.3.json

Gathering Tools Release v1.1.3

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.11.json

Fishing Buddy Release v1.0.11

---

manifests/ecksofa/gatheringtools/1.2.0.json

Gathering Tools Release v1.2.0

---

manifests/Denrage/AchievementTrackerModule/0.1.0.json

Achievement Tracker Release v0.1.0

---

manifests/pentose/itemsearch/0.3.2.json

Item Search Release v0.3.2

---

manifests/Denrage/AchievementTrackerModule/0.1.1.json

Achievement Tracker Release v0.1.1

---

manifests/Nekres/Stream_Out/0.6.2.json

Stream Out Release v0.6.2

---

manifests/Nekres/Inquest_Module/0.4.1.json

Inquest Chipset Release v0.4.1

---

manifests/Nekres/Chat_Shorts/0.2.1.json

Chat Shorts Release v0.2.1

---

manifests/Nekres/Stream_Out/0.7.2.json

Stream Out Release v0.7.2

---

manifests/bh/general/loadingscreenhints/1.0.4.json

Loading Screen Hints Release v1.0.4

---

manifests/Nekres/Stream_Out/0.7.3.json

Stream Out Release v0.7.3

---

manifests/pentose/itemsearch/0.3.3.json

Item Search Release v0.3.3

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.12.json

Fishing Buddy Release v1.0.12

---

manifests/Kenedia/Modules/Characters/0.2.10.json

Characters Release v0.2.10

---

manifests/ecksofa/gatheringtools/1.3.0.json

Gathering Tools Release v1.3.0

---

manifests/Denrage/AchievementTrackerModule/0.1.2.json

Achievement Tracker Release v0.1.2

---

manifests/pentose/itemsearch/0.3.4.json

Item Search Release v0.3.4

---

manifests/Kenedia/Modules/BuildsManager/0.0.16.json

Builds Manager Release v0.0.16

---

manifests/pentose/itemsearch/0.3.5.json

Item Search Release v0.3.5

---

manifests/bh/community/pathing/0.18.20.json

Pathing Release v0.18.20

---

manifests/Manlaan/Mounts/1.2.17.json

Mounts Release v1.2.17

---

manifests/Kenedia/Modules/BuildsManager/0.0.17.json

Builds Manager Release v0.0.17

---

manifests/Kenedia/Modules/QoL/0.0.3.json

Tyrian QoL Release v0.0.3

---

manifests/Ideka/HitboxView/1.1.0.json

Hitbox View Release v1.1.0

---

manifests/Ideka/HitboxView/1.2.0.json

Hitbox View Release v1.2.0

---

manifests/bh/community/pathing/0.18.22.json

Pathing Release v0.18.22

---

manifests/Denrage/AchievementTrackerModule/0.1.3.json

Achievement Tracker Release v0.1.3

---

manifests/Kenedia/Modules/BuildsManager/0.0.19.json

Builds Manager Release v0.0.19

---

manifests/Kenedia/Modules/QoL/0.0.6.json

Tyrian QoL Release v0.0.6

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.13.json

Fishing Buddy Release v1.0.13

---

manifests/Kenedia/Modules/QoL/0.0.7.json

Tyrian QoL Release v0.0.7

---

manifests/Kenedia/Modules/QoL/0.0.8.json

Tyrian QoL Release v0.0.8

---

manifests/Kenedia/Modules/Characters/0.2.11.json

Characters Release v0.2.11

---

manifests/bh/community/pathing/0.18.24.json

Pathing Release v0.18.24

---

manifests/Charr/Timers_BlishHUD/0.3.12.json

Timers Release v0.3.12

---

manifests/pentose/itemsearch/0.4.0.json

Item Search Release v0.4.0

---

manifests/pentose/itemsearch/0.4.1.json

Item Search Release v0.4.1

---

manifests/pentose/itemsearch/0.4.2.json

Item Search Release v0.4.2

---

manifests/Kenedia/Modules/Characters/0.2.12.json

Characters Release v0.2.12

---

manifests/ecksofa/gatheringtools/1.3.1.json

Gathering Tools Release v1.3.1

---

manifests/Charr/Timers_BlishHUD/0.3.13.json

Timers Release v0.3.13

---

manifests/estreya/bh/eventTable/1.8.1.json

Event Table Release v1.8.1

---

manifests/Charr/Timers_BlishHUD/0.3.15.json

Timers Release v0.3.15

---

manifests/Kenedia/Modules/BuildsManager/0.0.20.json

Builds Manager Release v0.0.20

---

manifests/bh/community/pathing/1.0.0.json

Pathing Release v1.0.0

---

manifests/Nekres/Music_Mixer/0.5.7.json

Music Mixer Release v0.5.7

---

manifests/Nekres/Musician_Module/0.8.3.json

Minstrel Protocol Release v0.8.3

---

manifests/Nekres/Screenshot_Manager/0.4.7.json

Screenshot Manager Release v0.4.7

---

manifests/Nekres/Music_Mixer/0.5.8.json

Music Mixer Release v0.5.8

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.14.json

Fishing Buddy Release v1.0.14

---

manifests/pentose/itemsearch/0.5.0.json

Item Search Release v0.5.0

---

manifests/Nekres/Mistwar/0.5.6.json

Mistwar Release v0.5.6

---

manifests/Nekres/Mistwar/0.5.9.json

Mistwar Release v0.5.9

---

manifests/Manlaan/Mounts/1.2.19.json

Mounts Release v1.2.19

---

manifests/Nekres/Music_Mixer/0.5.9.json

Music Mixer Release v0.5.9

---

manifests/ecksofa/gatheringtools/1.3.2.json

Gathering Tools Release v1.3.2

---

manifests/valorayne/bh/todos/1.0.1.json

Todos Release v1.0.1

---

manifests/pentose/itemsearch/0.5.1.json

Item Search Release v0.5.1

---

manifests/Nekres/Music_Mixer/0.6.1.json

Music Mixer Release v0.6.1

---

manifests/Nekres/Mistwar/0.6.0.json

Mistwar Release v0.6.0

---

manifests/Nekres/Music_Mixer/0.6.2.json

Music Mixer Release v0.6.2

---

manifests/Soeed/RaidClears/1.1.2.json

Raid Clears Release v1.1.2

---

manifests/Nekres/Mumble_Info/0.3.0.json

Mumble Info Release v0.3.0

---

manifests/Nekres/Music_Mixer/0.6.3.json

Music Mixer Release v0.6.3

---

manifests/Nekres/Mumble_Info/0.3.1.json

Mumble Info Release v0.3.1

---

manifests/Denrage/AchievementTrackerModule/0.1.4.json

Achievement Tracker Release v0.1.4

---

manifests/Soeed/RaidClears/1.2.0.json

Raid Clears Release v1.2.0

---

manifests/falcon/cmtracker/1.1.1.json

SSRD Build Triggered by Falcon

CM Tracker Release v1.1.1

---

manifests/valorayne/bh/todos/1.0.2.json

Todos Release v1.0.2

---

manifests/Ideka/MistsQuill/2.0.0-beta.json

Quill of the Mists Release v2.0.0-beta

---

manifests/Ideka/MistsQuill/2.0.1-beta.json

Quill of the Mists Release v2.0.1-beta

---

manifests/Ideka/MistsQuill/2.0.2-beta.json

Quill of the Mists Release v2.0.2-beta

---

manifests/Nekres/Mumble_Info/0.3.2.json

Mumble Info Release v0.3.2

---

manifests/Ideka/MistsQuill/2.0.3.json

Quill of the Mists Release v2.0.3

---

manifests/Nekres/Stream_Out/0.7.4.json

Stream Out Release v0.7.4

---

manifests/Nekres/Music_Mixer/0.9.7.json

Music Mixer Release v0.9.7

---

manifests/Nekres/Mistwar/0.9.5.json

Mistwar Release v0.9.5

---

manifests/Ideka/RacingMeter/1.4.0.json

Racing Meter Release v1.4.0

---

manifests/Nekres/Mistwar/0.9.8.json

Mistwar Release v0.9.8

---

manifests/ecksofa/sessiontracker/1.0.6.json

Session Tracker Release v1.0.6

---

manifests/Nekres/Mistwar/1.0.0.json

Mistwar Release v1.0.0

---

manifests/Charr/Timers_BlishHUD/0.3.16.json

Timers Release v0.3.16

---

manifests/Nekres/Chat_Shorts/0.3.4.json

Chat Shorts Release v0.3.4

---

manifests/Lorf/BH/TTBlockersStuff/0.1.0-alpha.json

TTBlockersStuff Release v0.1.0-alpha

---

manifests/Nekres/Mistwar/1.0.3.json

Mistwar Release v1.0.3

---

manifests/Charr/Timers_BlishHUD/0.3.17.json

Timers Release v0.3.17

---

manifests/ecksofa/sessiontracker/1.1.0.json

Session Tracker Release v1.1.0

---

manifests/Nekres/Regions_Of_Tyria/0.6.0.json

Regions of Tyria Release v0.6.0

---

manifests/Nekres/Mistwar/1.0.4.json

Mistwar Release v1.0.4

---

manifests/Lorf/BH/TTBlockersStuff/0.2.0-alpha.json

TTBlockersStuff Release v0.2.0-alpha

---

manifests/Nekres/Regions_Of_Tyria/0.6.3.json

Regions of Tyria Release v0.6.3

---

manifests/Nekres/Mistwar/1.0.7.json

Mistwar Release v1.0.7

---

manifests/Nekres/Stopwatch/0.2.0.json

Stopwatch Release v0.2.0

---

manifests/Nekres/Inquest_Module/0.4.2.json

Inquest Chipset Release v0.4.2

---

manifests/Nekres/Chat_Shorts/0.3.7.json

Chat Shorts Release v0.3.7

---

manifests/Nekres/Stream_Out/0.7.6.json

Stream Out Release v0.7.6

---

manifests/ecksofa/sessiontracker/1.1.2.json

Session Tracker Release v1.1.2

---

manifests/Nekres/Chat_Shorts/0.3.8.json

Chat Shorts Release v0.3.8

---

manifests/Nekres/Music_Mixer/0.9.9.json

Music Mixer Release v0.9.9

---

manifests/Nekres/Mumble_Info/0.3.4.json

Mumble Info Release v0.3.4

---

manifests/Nekres/Chat_Shorts/0.4.3.json

Chat Shorts Release v0.4.3

---

manifests/Ideka/MistsQuill/2.2.0.json

Quill of the Mists Release v2.2.0

---

manifests/Kenedia/Modules/QoL/0.0.9.json

Tyrian QoL Release v0.0.9

---

manifests/Charr/Timers_BlishHUD/0.3.18.json

Timers Release v0.3.18

---

manifests/Nekres/Regions_Of_Tyria/0.6.6.json

Regions of Tyria Release v0.6.6

---

manifests/Nekres/Mistwar/1.1.0.json

Mistwar Release v1.1.0

---

manifests/Nekres/Inquest_Module/0.4.13.json

Inquest Chipset Release v0.4.13

---

manifests/Ideka/RacingMeter/1.5.0.json

Racing Meter Release v1.5.0

---

manifests/Soeed/RaidClears/1.3.0.json

Raid Clears Release v1.3.0

---

manifests/Nekres/Inquest_Module/0.5.0.json

Inquest Chipset Release v0.5.0

---

manifests/bh/general/compass/3.1.0.json

Compass Release v3.1.0

---

manifests/bh/general/events/1.0.0.json

Events and Metas Observer Release v1.0.0

---

manifests/falcon/cmtracker/1.1.2.json

SSRD Build Triggered by Falcon

CM Tracker Release v1.1.2

---

manifests/Soeed/RaidClears/1.4.0.json

Raid Clears Release v1.4.0

---

manifests/Kenedia/Modules/BuildsManager/0.0.21.json

Builds Manager Release v0.0.21

---

manifests/Charr/Timers_BlishHUD/0.3.20.json

Timers Release v0.3.20

---

manifests/Soeed/RaidClears/1.4.1.json

Raid Clears Release v1.4.1

---

manifests/Lorf/BH/TTBlockersStuff/0.3.0-alpha.json

TTBlockersStuff Release v0.3.0-alpha

---

manifests/Teh/BHUD/Blacklist_Buddy_Module/0.0.2.json

Blacklist Buddy Release v0.0.2

---

manifests/bh/community/pathing/1.1.5.json

Pathing Release v1.1.5

---

manifests/Teh/BHUD/Blacklist_Buddy_Module/0.0.3.json

Blacklist Buddy Release v0.0.3

---

manifests/Ideka/RacingMeter/1.6.0.json

Racing Meter Release v1.6.0

---

manifests/Ideka/MistsQuill/2.2.1.json

Quill of the Mists Release v2.2.1

---

manifests/Nekres/Stopwatch/0.3.0.json

Stopwatch Release v0.3.0

---

manifests/bh/community/pathing/1.1.10.json

Pathing Release v1.1.10

---

manifests/Ideka/RacingMeter/1.6.1.json

Racing Meter Release v1.6.1

---

manifests/Teh/BHUD/Blacklist_Buddy_Module/0.0.4.json

Blacklist Buddy Release v0.0.4

---

manifests/Nekres/Stream_Out/0.7.8.json

Stream Out Release v0.7.8

---

manifests/Nekres/Screenshot_Manager/0.5.1.json

Screenshot Manager Release v0.5.1

---

manifests/Nekres/Screenshot_Manager/0.5.2.json

Screenshot Manager Release v0.5.2

---

manifests/valorayne/bh/todos/1.1.0.json

Todos Release v1.1.0

---

manifests/valorayne/bh/todos/1.1.1.json

Todos Release v1.1.1

---

manifests/valorayne/bh/todos/1.1.2.json

Todos Release v1.1.2

---

manifests/Denrage/AchievementTrackerModule/0.1.5.json

Achievement Tracker Release v0.1.5

---

manifests/Nekres/RotationTrainer/0.4.11.json

Special Forces Release v0.4.11

---

manifests/Nekres/RotationTrainer/0.4.12.json

Special Forces Release v0.4.12

---

manifests/Nekres/Stream_Out/0.7.9.json

Stream Out Release v0.7.9

---

manifests/Kenedia/Modules/BuildsManager/0.0.23.json

Builds Manager Release v0.0.23

---

manifests/estreya/bh/liveMap/0.10.0.json

Live Map Release v0.10.0

---

manifests/Nekres/Stream_Out/0.7.11.json

Stream Out Release v0.7.11

---

manifests/Ideka/RacingMeter/1.8.0-beta.json

Racing Meter Release v1.8.0-beta

---

manifests/Ideka/MistsQuill/2.3.0.json

Quill of the Mists Release v2.3.0

---

manifests/Ideka/RacingMeter/1.8.2-beta.json

Racing Meter Release v1.8.2-beta

---

manifests/estreya/bh/liveMap/1.0.0.json

Live Map Release v1.0.0

---

manifests/estreya/bh/eventTable/2.2.0.json

Event Table Release v2.2.0

---

manifests/Kenedia/Modules/Characters/1.0.0.json

Characters Release v1.0.0

---

manifests/Kenedia/Modules/Characters/1.0.1.json

Characters Release v1.0.1

---

manifests/Kenedia/Modules/Characters/1.0.2.json

Characters Release v1.0.2

---

manifests/Kenedia/Modules/Characters/1.0.3.json

Characters Release v1.0.3

---

manifests/Kenedia/Modules/ReleaseTheChoya/0.0.3.json

RELEASE TEH CHOYA! Release v0.0.3

---

manifests/Kenedia/Modules/Characters/1.0.4.json

Characters Release v1.0.4

---

manifests/Kenedia/Modules/Characters/1.0.6.json

Characters Release v1.0.6

---

manifests/estreya/bh/eventTable/2.3.0.json

Event Table Release v2.3.0

---

manifests/Soeed/RaidClears/2.0.1.json

Clears Tracker Release v2.0.1

---

manifests/Soeed/RaidClears/2.0.2.json

Clears Tracker Release v2.0.2

---

manifests/estreya/bh/eventTable/2.4.0.json

Event Table Release v2.4.0

---

manifests/Kenedia/Modules/Characters/1.0.7.json

Characters Release v1.0.7

---

manifests/ecksofa/sessiontracker/1.3.0.json

Session Tracker Release v1.3.0

---

manifests/Taimi/UndaDaSea_BlishHUD/2.0.2.json

SSRD Build Triggered by Tiny Taimi

Unda Da Sea Release v2.0.2

---

manifests/bh/community/pathing/1.1.13.json

Pathing Release v1.1.13

---

manifests/Kenedia/Modules/Characters/1.0.8.json

Characters Release v1.0.8

---

manifests/estreya/bh/eventTable/2.5.0.json

Event Table Release v2.5.0

---

manifests/Kenedia/Modules/Characters/1.0.9.json

Characters Release v1.0.9

---

manifests/estreya/bh/eventTable/2.5.1.json

Event Table Release v2.5.1

---

manifests/estreya/bh/eventTable/2.5.2.json

Event Table Release v2.5.2

---

manifests/Kenedia/Modules/Characters/1.0.10.json

Characters Release v1.0.10

---

manifests/estreya/bh/liveMap/1.1.0.json

Live Map Release v1.1.0

---

manifests/estreya/bh/eventTable/2.5.3.json

Event Table Release v2.5.3

---

manifests/estreya/bh/scrollingCombatText/1.1.0.json

Scrolling Combat Text Release v1.1.0

---

manifests/Nekres/Music_Mixer/0.9.16.json

Music Mixer Release v0.9.16

---

manifests/estreya/bh/eventTable/3.0.0.json

Event Table Release v3.0.0

---

manifests/Denrage/AchievementTrackerModule/0.1.6.json

Achievement Tracker Release v0.1.6

---

manifests/Tortle/PlayerMarker/1.0.1.json

SSRD Build Triggered by LuckyTortle

Player Marker Release v1.0.1

---

manifests/estreya/bh/eventTable/3.0.1.json

Event Table Release v3.0.1

---

manifests/estreya/bh/eventTable/3.0.2.json

Event Table Release v3.0.2

---

manifests/estreya/bh/liveMap/1.2.0.json

Live Map Release v1.2.0

---

manifests/Tortle/PlayerMarker/1.1.0.json

SSRD Build Triggered by LuckyTortle

Player Marker Release v1.1.0

---

manifests/Nekres/Music_Mixer/0.9.18.json

Music Mixer Release v0.9.18

---

manifests/Ideka/MistsQuill/2.5.0.json

Quill of the Mists Release v2.5.0

---

manifests/Soeed/RaidClears/2.0.3.json

Clears Tracker Release v2.0.3

---

manifests/bh/community/pathing/1.1.15.json

Pathing Release v1.1.15

---

manifests/estreya/bh/eventTable/3.0.3.json

Event Table Release v3.0.3

---

manifests/Kenedia/Modules/Characters/1.0.11.json

Characters Release v1.0.11

---

manifests/Soeed/RaidClears/2.0.4.json

Clears Tracker Release v2.0.4

---

manifests/estreya/bh/eventTable/3.0.4.json

Event Table Release v3.0.4

---

manifests/Nekres/Regions_Of_Tyria/0.6.9.json

Regions of Tyria Release v0.6.9

---

manifests/bh/community/pathing/1.1.17.json

Pathing Release v1.1.17

---

manifests/Nekres/Regions_Of_Tyria/0.6.10.json

Regions of Tyria Release v0.6.10

---

manifests/estreya/bh/eventTable/3.0.6.json

Event Table Release v3.0.6

---

manifests/Nekres/Music_Mixer/0.9.23.json

Music Mixer Release v0.9.23

---

manifests/estreya/bh/eventTable/3.0.7.json

Event Table Release v3.0.7

---

manifests/Kenedia/Modules/Characters/1.0.13.json

Characters Release v1.0.13

---

manifests/Soeed/RaidClears/2.0.5.json

Clears Tracker Release v2.0.5

---

manifests/Kenedia/Modules/Characters/1.0.16.json

Characters Release v1.0.16

---

manifests/estreya/bh/webhookUpdater/1.2.0.json

Webhook Updater Release v1.2.0

---

manifests/Nekres/Stream_Out/0.9.1.json

Stream Out Release v0.9.1

---

manifests/Nekres/Stream_Out/0.9.4.json

Stream Out Release v0.9.4

---

manifests/Nekres/Stream_Out/0.9.7.json

Stream Out Release v0.9.7

---

manifests/Nekres/Stream_Out/0.9.8.json

Stream Out Release v0.9.8

---

manifests/Denrage/AchievementTrackerModule/0.1.7.json

Achievement Tracker Release v0.1.7

---

manifests/Nekres/Stream_Out/0.9.9.json

Stream Out Release v0.9.9

---

manifests/estreya/bh/eventTable/3.2.0.json

Event Table Release v3.2.0

---

manifests/Nekres/Mistwar/1.2.0.json

Mistwar Release v1.2.0

---

manifests/japyx/kprefresher/1.0.0.json

KpRefresher Release v1.0.0

---

manifests/Nekres/Mistwar/1.3.2.json

Mistwar Release v1.3.2

---

manifests/ecksofa/sessiontracker/1.3.1.json

Session Tracker Release v1.3.1

---

manifests/estreya/bh/eventTable/3.2.1.json

Event Table Release v3.2.1

---

manifests/ecksofa/gatheringtools/1.3.3.json

Gathering Tools Release v1.3.3

---

manifests/japyx/kprefresher/1.0.2.json

KpRefresher Release v1.0.2

---

manifests/estreya/bh/eventTable/3.3.0.json

Event Table Release v3.3.0

---

manifests/japyx/kprefresher/1.0.3.json

KpRefresher Release v1.0.3

---

manifests/Soeed/RaidClears/2.1.0.json

Clears Tracker Release v2.1.0

---

manifests/japyx/kprefresher/1.0.4.json

KpRefresher Release v1.0.4

---

manifests/japyx/kprefresher/1.1.0.json

KpRefresher Release v1.1.0

---

manifests/Ideka/RacingMeter/1.8.4.json

Racing Meter Release v1.8.4

---

manifests/japyx/kprefresher/1.1.1.json

KpRefresher Release v1.1.1

---

manifests/japyx/kprefresher/1.1.2.json

KpRefresher Release v1.1.2

---

manifests/japyx/kprefresher/1.2.0.json

KpRefresher Release v1.2.0

---

manifests/estreya/bh/eventTable/3.3.1.json

Event Table Release v3.3.1

---

manifests/estreya/bh/liveMap/1.2.1.json

Live Map Release v1.2.1

---

manifests/Ideka/RacingMeter/1.9.1.json

Racing Meter Release v1.9.1

---

manifests/Nekres/Mistwar/1.4.2.json

Mistwar Release v1.4.2

---

manifests/estreya/bh/eventTable/3.4.0.json

Event Table Release v3.4.0

---

manifests/bh/general/universalsearch/0.8.0.json

Universal Search Release v0.8.0

---

manifests/estreya/bh/tradingPostWatcher/1.1.0.json

Trading Post Watcher Release v1.1.0

---

manifests/japyx/kprefresher/1.3.0.json

KpRefresher Release v1.3.0

---

manifests/Manlaan/Mounts/1.3.2.json

Mounts Release v1.3.2

---

manifests/ecksofa/gatheringtools/1.4.0.json

Gathering Tools Release v1.4.0

---

manifests/Eclipse1807/BlishHUD/FishingBuddy/1.0.15.json

Fishing Buddy Release v1.0.15

---

manifests/com/shooper/ddr/1.0.0.json

Dance Dance Rotation Release v1.0.0

---

manifests/com/shooper/ddr/1.0.1.json

Dance Dance Rotation Release v1.0.1

---

manifests/Soeed/RaidClears/2.2.0.json

Clears Tracker Release v2.2.0

---

manifests/Manlaan/Mounts/1.3.3.json

Mounts Release v1.3.3

---

manifests/estreya/bh/eventTable/3.4.1.json

Event Table Release v3.4.1

---

manifests/estreya/bh/tradingPostWatcher/1.1.1.json

Trading Post Watcher Release v1.1.1

---

manifests/Teh/BHUD/Blacklist_Buddy_Module/0.1.0.json

Blacklist Buddy Release v0.1.0

---

manifests/Soeed/RaidClears/2.2.1.json

Clears Tracker Release v2.2.1

---

manifests/japyx/kprefresher/1.4.0.json

KpRefresher Release v1.4.0

---

manifests/com/shooper/ddr/1.1.0.json

Dance Dance Rotation Release v1.1.0

---

manifests/KillProofModule/2.16.2.json

Proof Logix Release v2.16.2

---

manifests/Soeed/RaidClears/2.2.2.json

Clears Tracker Release v2.2.2

---

manifests/KillProofModule/2.16.8.json

Proof Logix Release v2.16.8

---

manifests/blackjacksoftware/blishhud/currencyviewer/0.3.0.json

SSRD Build Triggered by BlackjackKent

CurrencyViewer Release v0.3.0

---

manifests/blackjacksoftware/blishhud/currencyviewer/0.3.1.json

SSRD Build Triggered by BlackjackKent

CurrencyViewer Release v0.3.1

---

manifests/KillProofModule/2.17.2.json

Proof Logix Release v2.17.2

---

manifests/KillProofModule/2.17.4.json

Proof Logix Release v2.17.4

---

manifests/KillProofModule/2.18.0.json

Proof Logix Release v2.18.0

---

manifests/KillProofModule/2.18.1.json

Proof Logix Release v2.18.1

---

manifests/KillProofModule/2.18.5.json

Proof Logix Release v2.18.5

---

manifests/KillProofModule/2.18.10.json

Proof Logix Release v2.18.10

---

manifests/com/shooper/ddr/1.2.0.json

Dance Dance Rotation Release v1.2.0

---

manifests/KillProofModule/2.21.0.json

Proof Logix Release v2.21.0

---

manifests/japyx/kprefresher/1.5.0.json

KpRefresher Release v1.5.0

---

manifests/KillProofModule/2.21.1.json

Proof Logix Release v2.21.1

---

manifests/bh/community/pathing/1.2.5.json

Pathing Release v1.2.5

---

manifests/bh/community/pathing/1.2.6.json

Pathing Release v1.2.6

---

manifests/bh/community/pathing/1.2.8.json

Pathing Release v1.2.8

---

manifests/Nekres/Mistwar/1.4.5.json

Mistwar Release v1.4.5

---

manifests/estreya/bh/eventTable/3.4.2.json

Event Table Release v3.4.2
